
#libreria para deploy
```{r}
library(rsconnect)
```

```{r}
rsconnect::setAccountInfo(name='mgoconsulting',
			  token='2E44AF63CD391A87377F8069E65F35B9',
			  secret='dVPK1PmYMhrk8S8p33Cz3giqdvlyDmXVGvkl5tz9')
```

#libreria para crear

```{r}
library(shiny)
```
```{r}
runExample("01_hello")
```


#estructura de un app shiny, el UI y el SERVER, luego llamar con la funcion ShinyApp o runAPP

```{r}

# Define UI for app that draws a histogram ----
ui <- fluidPage(

  # App title ----
  titlePanel("Hello MGO!"),

  # Sidebar layout with input and output definitions ----
  sidebarLayout(

    # Sidebar panel for inputs ----
    sidebarPanel(

      # Input: Slider for the number of bins ----
      sliderInput(inputId = "bins",
                  label = "Number of bins:",
                  min = 1,
                  max = 50,
                  value = 30)

    ),

    # Main panel for displaying outputs ----
    mainPanel(

      # Output: Histogram ----
      plotOutput(outputId = "distPlot")

    )
  )
)
```

```{r}
# Define server logic required to draw a histogram ----
server <- function(input, output) {

  # Histogram of the Old Faithful Geyser Data ----
  # with requested number of bins
  # This expression that generates a histogram is wrapped in a call
  # to renderPlot to indicate that:
  #
  # 1. It is "reactive" and therefore should be automatically
  #    re-executed when inputs (input$bins) change
  # 2. Its output type is a plot
  output$distPlot <- renderPlot({

    x    <- faithful$waiting
    bins <- seq(min(x), max(x), length.out = input$bins + 1)

    hist(x, breaks = bins, col = "#75AADB", border = "white",
         xlab = "Waiting time to next eruption (in mins)",
         main = "Histogram of waiting times")

    })

}
```

```{r}
# See above for the definitions of ui and server
#ui <- ...

#server <- ...

shinyApp(ui = ui, server = server)
```


```{r}
library(shiny)
setwd("D:/Mego/Big_Data")
runApp("shiny1",launch.browser = getOption("shiny.launch.browser", interactive()))

```

mas ejemplos:
```{r}
runExample("01_hello")      # a histogram
runExample("02_text")       # tables and data frames
runExample("03_reactivity") # a reactive expression
runExample("04_mpg")        # global variables
runExample("05_sliders")    # slider bars
runExample("06_tabsets")    # tabbed panels
runExample("07_widgets")    # help text and submit buttons
runExample("08_html")       # Shiny app built from HTML
runExample("09_upload")     # file upload wizard
runExample("10_download")   # file download wizard
runExample("11_timer")      # an automated timer
```


#deploy en mi cuenta https://www.shinyapps.io/admin/#/dashboard

```{r}
rsconnect::deployApp('D:/Mego/Big_Data/shiny1')
```



