---
title: "R Notebook"
output: html_notebook
---

# https://anderfernandez.com/blog/reticulate-usar-python-en-r/
# https://stackoverflow.com/questions/52741484/how-to-import-pandas-using-r-studio


```{r}
library(reticulate)
```
instalaciones de python que tengo
```{r}
#conda_list()
```

```{r}
use_python("D:\\Temporal\\Anaconda\\python.exe",required = TRUE)
```


```{r}
py_config()
```
#para instalar paquetes de python
```{r}
#py_install("pandas")
```

```{python}
import numpy as np
import pandas as pd
```

```{python}
help(pd.Series)
```


```{python}
numbers = [1, 2, 3]
pd.Series(numbers)
```

```{python}
animals = ['Tiger', 'Bear', 'Moose']
pd.Series(animals)
```


```{python}
numbers = [1, 2, 3]
pd.Series(numbers)
```

```{python}
animals = ['Tiger', 'Bear', None]
pd.Series(animals)
```


```{python}
np.nan == None
np.nan == np.nan
np.isnan(np.nan)
```

```{python}
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s
```


```{python}
s.index
```


```{python}
s = pd.Series(['Tiger', 'Bear', 'Moose'], index=['India', 'America', 'Canada'])
s
```


```{python}
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports, index=['Golf', 'Sumo', 'Hockey'])
s
```
Querying a Series
```{python}
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s
```


```{python}
s.iloc[3]
s.loc['Golf']
s[3]
s['Golf']
```


```{python}
sports = {99: 'Bhutan',
          100: 'Scotland',
          101: 'Japan',
          102: 'South Korea'}
s = pd.Series(sports)
```

```{python}
s[0] #This won't call s.iloc[0] as one might expect, it generates an error instead
```


```{python}
s = pd.Series([100.00, 120.00, 101.00, 3.00])
type(s)
```


```{python}
total = 0
for item in s:
    total=total+item
print(total)
```


```{python}
total = np.sum(s)
print(total)
```
#this creates a big series of random numbers

```{python}
s1 = pd.Series(np.random.randint(0,1000,10000))
s1.head()
```

```{python}
len(s1)
```
```{python}
summary = 0
for item in s1:
    summary=summary+item
summary
```


```{python}
summary = np.sum(s1)
summary
```

```{python}
s = pd.Series([1, 2, 3])
s.loc['Animal'] = 'Bears'
s
```

```{python}
original_sports = pd.Series({'Archery': 'Bhutan',
                             'Golf': 'Scotland',
                             'Sumo': 'Japan',
                             'Taekwondo': 'South Korea'})
cricket_loving_countries = pd.Series(['Australia',
                                      'Barbados',
                                      'Pakistan',
                                      'England'], 
                                   index=['Cricket',
                                          'Cricket',
                                          'Cricket',
                                          'Cricket'])
all_countries = original_sports.append(cricket_loving_countries)
```


```{python}
original_sports
cricket_loving_countries
all_countries
all_countries.loc['Cricket']
```

#The DataFrame Data Structure

```{python}
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})
df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])
df.head()
```

```{python}

```


```{python}

```

```{python}

```


```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```





```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```




```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```



```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```


```{python}

```

```{python}

```